include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-performance-manager
PKG_VERSION:=1.0.0-rc.2
PKG_RELEASE:=1
PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=OpenWrt Performance Manager contributors

LUCI_TITLE:=LuCI support for OpenWrt Performance Manager
LUCI_DEPENDS:=+luci-base +rpcd +performance-manager
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
